datamodule: 
  batch_size: 32
  num_workers: 4

model:
  warmup_steps: 10000
  label_smoothing: 0.1
  d_model: 128
  max_seq_len: 5000
  h: 8
  d_ff: 512
  p_drop: 0.3
  N: 2
  betas: [0.9, 0.98]
  eps: 1e-9

trainer:
  max_epochs: 20